name: Change shell
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh          # シェルにBashを指定
        run: echo "${SHELL}"
      - shell: python        # シェルにPythonを指定
        run: |
          import os
          print(os.environ['PATH'])